### ISSUE TITLE
Change config file standards

### ISSUE THREAD

**Issue by Homosanians** [RuverQ/CauldronBrew#2]
Writing words together is often not a good idea. This will make it difficult to understand the file fluently. Naming styles were created for that exact purpose. Here're some of them: camelCase, PascalCase, snake_case, dash-case. There is no single convention for the YAML naming style, different projects choose them as they see fit.

PascalCase is already reversed (most people) for objects definition in YAML, so I suggest using the camelCase. The result of use is reflected below.

Secondly, comments. I do recommend the following set of rules. They are optional, but it seems to me that they are more beautiful.

- 1 space must be added after the comment mark
- the sentence must begin with a capital letter.

original
```yml
Localization: en

#Main Settings of cauldron
Cauldron:
  secondstoboil: 10
  blocktoupgrage: iron_block
  maxitemsincauldron: 32

#Event PlayerDropItem and checks where item is to drop in cauldron
dropitem:
  checknearbycauldron:
    delay: 5
    radius: 0.1
    secondstocheck: 20

#Holograms in SUPERALPHA!!!!
Hologram:
  enabled: false
  visiblinradius:
    enabled: true
    radius: 10
  floating:
    enabled: true
    distance: 0.2

#dont touch
configversion: 0.1
```

using these rules
```yml
Localization: en

# Main Settings of cauldron
Cauldron:
  secondsToBoil: 10
  blockToUpgrage: iron_block
  maxItemsInCauldron: 32

# Event PlayerDropItem and checks where item is to drop in cauldron
dropItem:
  checkNearByCauldron:
    delay: 5
    radius: 0.1
    secondsToCheck: 20

# Holograms in SUPERALPHA!!!!
Hologram:
  enabled: false
  visibleInRadius:
    enabled: true
    radius: 10
  floating:
    enabled: true
    distance: 0.2

# Don't touch
configVersion: 0.1
```
